<?php
$title = $this->translate('Contact us');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('contact', array('action' => 'send')));

$form->prepare();
echo $this->form()->openTag($form);

echo $this->formRow($form->get('firstname'));
echo $this->formRow($form->get('lastName'));
echo $this->formRow($form->get('email'));
echo $this->formRow($form->get('phone'));
echo $this->formRow($form->get('message'));
echo $this->formRow($form->get('captcha'));
echo $this->formSubmit($form->get('submit'));

echo $this->form()->closeTag();
?>