<?php
$title = $this->translate('Contact us');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('contact', array('action' => 'send')));

$form->prepare();
echo $this->form()->openTag($form);

echo "<p>".$this->formRow($form->get('firstname'))."</p>";
echo "<p>".$this->formRow($form->get('lastName'))."</p>";
echo "<p>".$this->formRow($form->get('email'))."</p>";
echo "<p>".$this->formRow($form->get('phone'))."</p>";
echo "<p>".$this->formRow($form->get('message'))."</p>";
echo "<p>".$this->formRow($form->get('captcha'))."</p>";
echo "<p>".$this->formSubmit($form->get('submit'))."</p>";

echo $this->form()->closeTag();
?>