<?php
$title = $this->translate('Add new drug');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('medicaments', array('action' => 'add')));

$form->prepare();
echo $this->form()->openTag($form);

echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('molecule'));
echo $this->formRow($form->get('indications'));
echo $this->formRow($form->get('cons_indications'));
echo $this->formSubmit($form->get('submit'));

echo $this->form()->closeTag();
?>