<?php
$title = $this->translate('Add new drug');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('medicaments', array('action' => 'add')));

$form->prepare();
echo $this->form()->openTag($form);

echo "<p>".$this->formHidden($form->get('id'))."</p>";
echo "<p>".$this->formRow($form->get('name'))."</p>";
echo "<p>".$this->formRow($form->get('molecule'))."</p>";
echo "<p>".$this->formRow($form->get('indications'))."</p>";
echo "<p>".$this->formRow($form->get('cons_indications'))."</p>";
echo "<p>".$this->formSubmit($form->get('submit'))."</p>";

echo $this->form()->closeTag();
?>
