<?php
$title = $this->translate('Delete drug');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p><?php echo $this->translate('Are you sure that you want to delete'); ?>
    '<?php echo $this->escapeHtml($medicament->name); ?>'?
</p>
<?php
$url = $this->url('medicaments', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
	<div>
	    <input type="hidden" name="id" value="<?php echo (int)$medicament->id; ?>" />
	    <input type="submit" name="del" value="<?php echo $this->translate('Yes'); ?>" />
	    <input type="submit" name="del" value="<?php echo $this->translate('No'); ?>" />
	</div>
</form>