<?php
$title = 'Edit drug (id ' . $id . ')';
$this->headTitle($title);
echo '<h1>' . $this->escapeHtml($title) . '</h1>';

$form = $this->form;
$form->setAttribute('action', $this->url('medicaments', array('action' => 'edit', 'id' => $this->id,)));

$form->prepare();
echo $this->form()->openTag($form);

echo "<p>".$this->formHidden($form->get('id'))."</p>";
echo "<p>".$this->formRow($form->get('name'))."</p>";
echo "<p>".$this->formRow($form->get('molecule'))."</p>";
echo "<p>".$this->formRow($form->get('indications'))."</p>";
echo "<p>".$this->formRow($form->get('cons_indications'))."</p>";
echo "<p>".$this->formSubmit($form->get('submit'))."</p>";

echo $this->form()->closeTag();
?>