Action "index", controller "Index", module "Medicaments".
<br />

<?php echo $this->translate('Configuration file'); ?>

<?php
// Setting the URL for the form's action
$form->setAttribute('action', $this->url('medicaments', array('action' => 'changeConfiguration')));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formRow($form->get('config_file'));
echo $this->formRow($form->get('environment'));
echo '<br />';
echo $this->formSubmit($form->get('submit'));
// Alternative method: replace everything between openTag and closeTag with $this->formCollection($form);
echo $this->form()->closeTag();

// List all drugs
?>
<table class="table table-bordered table-striped">
<tr>
    <th>ID</th>
    <th>Name</th>
    <th>&nbsp;</th>
    <th>&nbsp;</th>
</tr>
<?php
foreach ($medicaments as $medicament)
{
?>
	<tr>
	    <td><?php echo $this->escapeHtml($medicament->id);?></td>
	    <td><?php echo $this->escapeHtml($medicament->name);?></td>
	    <td>
	        <a href="<?php echo $this->url('medicaments', array('action'=>'edit', 'id' => $medicament->id)); ?>">
	        	Edit
	        </a>
	    </td>
	    <td>
	        <a href="<?php echo $this->url('medicaments', array('action'=>'delete', 'id' => $medicament->id));?>">
	        	Delete
	        </a>
	    </td>
	</tr>
<?php } ?>
</table>