<?php
$title = 'Add new drug';
$this->headTitle($title);
echo '<h1>' . $this->escapeHtml($title) . '</h1>';
?>

<?php
// List all drugs
?>
<table class="table table-bordered table-striped">
<tr>
    <th>ID</th>
    <th>Name</th>
    <th>&nbsp;</th>
    <th>&nbsp;</th>
</tr>
<?php
foreach ($medicaments as $medicament)
{
?>
	<tr>
	    <td><?php echo $this->escapeHtml($medicament->id);?></td>
	    <td><?php echo $this->escapeHtml($medicament->name);?></td>
	    <td>
	        <a href="<?php echo $this->url('medicaments', array('action'=>'edit', 'id' => $medicament->id)); ?>">
	        	Edit
	        </a>
	    </td>
	    <td>
	        <a href="<?php echo $this->url('medicaments', array('action'=>'delete', 'id' => $medicament->id));?>">
	        	Delete
	        </a>
	    </td>
	</tr>
<?php } ?>
</table>

<?php
// Add new drug
?>
<a href="<?php echo $this->url('medicaments', array('action' => 'add')); ?>"><?php echo $this->translate('Add new drug'); ?></a>