<?php
$title = $this->translate('Configuration file');
$this->headTitle($title);
echo '<h1>' . $this->escapeHtml($title) . '</h1>';
?>


<?php
// List all drugs
?>
<table class="table table-bordered table-striped">
<tr>
    <th><?php echo $this->translate('File type'); ?></th>
    <th><?php echo $this->translate('Environment'); ?></th>
    <th>&nbsp;</th>
</tr>
<?php
foreach ($configurations as $configuration)
{
?>
	<tr>
		<td><?php echo $this->escapeHtml($configuration->config_file);?></td>
		<td><?php echo $this->escapeHtml($configuration->environment);?></td>
	    <td>
	    	<form action="<?php echo $this->url('configuration', array('action' => 'changeConfiguration')); ?>" method="post">
	    		<input type="hidden" name="id" value="<?php echo (int)$configuration->id; ?>" />
	    		<input type="hidden" name="config_file" value="<?php echo $configuration->config_file; ?>" />
	    		<input type="hidden" name="environment" value="<?php echo $configuration->environment; ?>" />
		    	<input type="submit" name="use" value="<?php echo $this->translate('Use this file'); ?>" />
		    </form>
	    </td>
	</tr>
<?php } ?>
</table>