<?php echo $this->translate('Configuration file'); ?>

<?php
// Setting the URL for the form's action
$form->setAttribute('action', $this->url('configuration', array('action' => 'changeConfiguration')));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formRow($form->get('config_file'));
echo $this->formRow($form->get('environment'));
echo '<br />';
echo $this->formSubmit($form->get('submit'));
// Alternative method: replace everything between openTag and closeTag with $this->formCollection($form);
echo $this->form()->closeTag();
?>