<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('medicaments') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Skeleton Application') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('medicaments') ?>"><?php echo $this->translate('Home') ?></a></li>
                        <li><a href="<?php echo $this->url('configuration') ?>"><?php echo $this->translate('Configuration') ?></a></li>
                        <li><a href="<?php echo $this->url('contact') ?>"><?php echo $this->translate('Contact') ?></a></li>
                        <li><a href="<?php echo $this->url('rss') ?>"><?php echo $this->translate('RSS') ?></a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <?php echo $this->translate('Language'); ?>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="<?php echo $this->url('language', array('action' => 'index', 'id' => '1')); ?>">
                                        <?php echo $this->translate('French'); ?>
                                    </a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->url('language', array('action' => 'index', 'id' => '2')); ?>">
                                        <?php echo $this->translate('English'); ?>
                                    </a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->url('language', array('action' => 'index', 'id' => '3')); ?>">
                                        <?php echo $this->translate('Spanish'); ?>
                                    </a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->url('language', array('action' => 'index', 'id' => '4')); ?>">
                                        <?php echo $this->translate('Deutsch'); ?>
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2013 - <?php echo date('Y') ?> <?php echo $this->translate('by'); ?> Axel Bouaziz, Philipp Traing, Jose Albea <?php echo $this->translate('and'); ?> Yohann Teisseire. <?php echo $this->translate('All rights reserved.') ?></p>
                <p>
                    <?php
                    
                    ?>
                </p>
                <?php
                // Debugging controller, action and view into the footer
                Zend\Debug\Debug::dump($controllerName, $this->translate('controller'));
                Zend\Debug\Debug::dump($actionName, $this->translate('action'));
                Zend\Debug\Debug::dump($actionName, $this->translate('view'));

                // Logging these vars into a file
                $logger = new Zend\Log\Logger;
                $writer = new Zend\Log\Writer\Stream('./var/log/debug.log');
                $logger->addWriter($writer);                
                $logger->debug('Controller: ' . $controllerName . ' - Action: ' . $actionName . ' - View: ' . $actionName);
                ?>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
