<?php if ($this->pageCount){ ?>
    <div class="pagination pagination-centered">
            <!-- Previous page link -->
            <?php if (isset($this->previous)){ ?>
                    <a href="<?php echo $this->url($this->route); ?>?page=<?php echo $this->previous; ?>">
                        <?php echo $this->translate('Previous'); ?>
                    </a>
            <?php }else{ ?>
                    <a href="#">
                        <?php echo $this->translate('Previous'); ?>
                    </a>
            <?php } ?>
            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page){ ?>
                <?php if ($page != $this->current){ ?>
                        <a href="<?php echo $this->url($this->route);?>?page=<?php echo $page; ?>">
                            <?php echo $page; ?>
                        </a>
                <?php }else{ ?>
                        <a href="#"><?php echo $page; ?></a>
                <?php } ?>
            <?php } ?>

            <!-- Next page link -->
            <?php if (isset($this->next)){ ?>
                    <a href="<?php echo $this->url($this->route); ?>?page=<?php echo $this->next; ?>">
                        <?php echo $this->translate('Next'); ?>
                    </a>
            <?php }else{ ?>
                    <a href="#">
                        <?php echo $this->translate('Next'); ?>
                    </a>
            <?php } ?>
    </div>
<?php } ?>