<?php if ($this->pageCount){ ?>
    <div class="pagination pagination-centered">
            <!-- Previous page link -->
            <ul class="pagination">
            <?php if (isset($this->previous)){ ?>
                <!-- <button type="button" class="btn btn-link"> -->
                <li>
                    <a href="<?php echo $this->url($this->route); ?>?page=<?php echo $this->previous; ?>">
                        <?php echo $this->translate('Previous'); ?>
                    </a>
                </li>
                <!-- </button> -->
            <?php }else{ ?>
                <!-- <button class="btn btn-link disabled"> -->
                    <li class="disabled">
                        <a href="#">
                            <?php echo $this->translate('Previous'); ?>
                        </a>
                    </li>
                <!-- </button> -->
            <?php } ?>
            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page){ ?>
                <?php if ($page != $this->current){ ?>
                    <!-- <button type="button" class="btn btn-link"> -->
                        <li>
                            <a href="<?php echo $this->url($this->route);?>?page=<?php echo $page; ?>">
                                <?php echo $page; ?>
                            </a>
                        </li>
                    <!-- </button> -->
                <?php }else{ ?>
                    <!-- <button type="button" class="btn btn-link active"> -->
                        <li class="active">
                            <a href="#"><?php echo $page; ?></a>
                        </li>
                    <!-- </button> -->
                <?php } ?>
            <?php } ?>

            <!-- Next page link -->
            <?php if (isset($this->next)){ ?>
                <!-- <button type="button" class="btn btn-link"> -->
                    <li>
                        <a href="<?php echo $this->url($this->route); ?>?page=<?php echo $this->next; ?>">
                            <?php echo $this->translate('Next'); ?>
                        </a>
                    </li>
                <!-- </button> -->
            <?php }else{ ?>
                <!-- <button type="button" class="btn btn-link disabled"> -->
                    <li class="disabled">
                        <a href="#">
                            <?php echo $this->translate('Next'); ?>
                        </a>
                    </li>
                <!-- </button> -->
            <?php } ?>
        </ul>
    </div>
<?php } ?>